### ISSUE TITLE
i have no idea how to install

### ISSUE THREAD

**Issue by noamiko2004** [alekxeyuk/Skribbl.io-Bot#34]
i dont know what is Dependencies and all that stuff please help me

**Comment by fuck-shithub** [comment]
1. Download and install Python 3 (https://www.python.org/downloads/) and make sure environment variables are set up
1. Download and install Git from https://git-scm.com/download/win.
1. Download this repository as zip (or via Git). Or just open this link: https://github.com/alekxeyuk/Skribbl.io-Bot/archive/master.zip
1. Extract to some folder somewhere
1. Get inside the folder and press Shift + Right Click anywhere where there is no file/folder in the File Explorer window
1. "Open PowerShell right here" or whatever the option was called again. If it says "command prompt" instead that's fine as well
1. Run this command:
```
pip install websockets aiohttp python-socketio requests git+https://www.github.com/hbldh/hitherdither Pillow google_images_download numpy
```
7. Open loop.bat to run the thing.

**Comment by m0caa** [comment]
This is the error i'm getting when I try use the command

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w4N4v1/websockets/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w4N4v1/websockets/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-w4N4v1/websockets/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-w4N4v1/websockets/setup.py", line 24, in <module>
        raise Exception("websockets requires Python >= 3.4.")
    Exception: websockets requires Python >= 3.4.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
